-- Local development seed stocks for manual trading tests.
-- Safe to rerun: existing channel_id rows are updated in place.

INSERT INTO stocks (
    channel_id,
    streamer_name,
    profile_image_url,
    follower_count,
    base_broadcast_hours,
    total_supply,
    daily_volume,
    base_price,
    current_price,
    is_live,
    live_started_at,
    dividend_accumulation_count,
    issued_shares,
    pre_stream_float,
    created_at,
    listed_at
) VALUES
    (
        'dev-blue-chip',
        'Dev Blue Chip',
        NULL,
        250000,
        1200,
        100000,
        0,
        10000,
        10000,
        FALSE,
        NULL,
        0,
        0,
        0,
        NOW(),
        NOW()
    ),
    (
        'dev-mid-cap',
        'Dev Mid Cap',
        NULL,
        55000,
        480,
        100000,
        0,
        25000,
        28000,
        FALSE,
        NULL,
        0,
        0,
        0,
        NOW(),
        NOW()
    ),
    (
        'dev-live-stream',
        'Dev Live Stream',
        NULL,
        120000,
        900,
        100000,
        0,
        50000,
        65000,
        TRUE,
        NOW(),
        0,
        0,
        0,
        NOW(),
        NOW()
    ),
    (
        'dev-overheated',
        'Dev Overheated',
        NULL,
        80000,
        300,
        100000,
        0,
        30000,
        210000,
        FALSE,
        NULL,
        0,
        0,
        0,
        NOW(),
        NOW()
    ),
    (
        'dev-cheap-test',
        'Dev Cheap Test',
        NULL,
        15000,
        160,
        100000,
        0,
        1000,
        1200,
        FALSE,
        NULL,
        0,
        0,
        0,
        NOW(),
        NOW()
    )
ON DUPLICATE KEY UPDATE
    streamer_name = VALUES(streamer_name),
    profile_image_url = VALUES(profile_image_url),
    follower_count = VALUES(follower_count),
    base_broadcast_hours = VALUES(base_broadcast_hours),
    total_supply = VALUES(total_supply),
    daily_volume = VALUES(daily_volume),
    base_price = VALUES(base_price),
    current_price = VALUES(current_price),
    is_live = VALUES(is_live),
    live_started_at = VALUES(live_started_at),
    dividend_accumulation_count = VALUES(dividend_accumulation_count),
    issued_shares = VALUES(issued_shares),
    pre_stream_float = VALUES(pre_stream_float),
    listed_at = VALUES(listed_at);

SELECT channel_id, streamer_name, current_price, base_price, total_supply, issued_shares, is_live
FROM stocks
WHERE channel_id LIKE 'dev-%'
ORDER BY current_price DESC;
