ALTER TABLE stocks
    MODIFY COLUMN current_price  BIGINT NOT NULL DEFAULT 0,
    MODIFY COLUMN base_price     BIGINT NOT NULL DEFAULT 0,
    MODIFY COLUMN listing_price  BIGINT NOT NULL DEFAULT 10000;
