ALTER TABLE users
    MODIFY coin_balance DECIMAL(30, 2) NOT NULL DEFAULT 0.00,
    MODIFY dividend_total DECIMAL(30, 2) NOT NULL DEFAULT 0.00,
    MODIFY realized_profit DECIMAL(30, 2) NOT NULL DEFAULT 0.00;
